#define  name of work flow 
name: my test workflows 

#define the trigger event(s)
on: [push]
# jobs run in parallel by default ,each staps in sequence 
jobs:
  say-hello:
    run-on: ubuntu-latest
    steps:
      - run: echo"Hello ,Github Actions!"